name: Generate App Meta JSON
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      
      - name: Generate JSON
        run: |
          export GIT_TOKEN="${{ secrets.AUTH_KEY }}"
          python generate.py "${{ secrets.TOKEN }}" > apps.json
          
      - name: Commit Changes
        run: |
          git config --global user.email "jimmyboehm@dergoogler.com"
          git config --global user.name "DG-Store-Service"
          git add apps.json
          git commit -sm "Update apps.json" || true
          git push || true
